# Generated by Django 4.0.6 on 2022-07-23 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Coupon unique code')),
                ('valid_from', models.DateTimeField(verbose_name='Valid from')),
                ('valid_to', models.DateTimeField(verbose_name='Valid to')),
                ('discount', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Discount')),
                ('active', models.BooleanField(verbose_name='Is active')),
            ],
        ),
    ]
